package com.sharktank.constants;

public enum PreviousInsurersEnum {
	HDFC_ERGO(1,"HDFC ERGO GENERAL INSURANCE CO LTD"),
	NEW_INDIA(2,"THE NEW INDIA ASSURANCE CO LTD"),
	ICICI_LOMBARD(3,"ICICI LOMBARD GENERAL INS. CO. LTD"),
	BAJAJ_ALLIANCE(4,"BAJAJ ALLIANZ GENERAL INS. CO. LTD"),
	NATIONAL_INSURANCE_CO(5,"NATIONAL INSURANCE CO.LTD"),
	ROYAL_SUNDARAM(6,"ROYAL SUNDARAM ALLIANCE INSU CO LTD"),
	FUTURE_GENERALI(7,"FUTURE GENERALI IND INSURANC CO LTD"),
	UNITED_INDIA(8,"UNITED INDIA INSURANCE"),
	IFFCO_TOKIO(9,"IFFCO TOKIO GENERAL INS. CO. LTD."),
	BHARTI_AXA(10,"BHARTI AXA GENERAL INSURANCE CO LTD"),
	TATA_AIG(11,"TATA AIG GENERAL INSURANCE CO. LTD."),
	RELIANCE_GENERAL(12,"RELIANCE GENERAL INSURANCE CO. LTD."),
	NATIONAL_INSURANCE(13,"NATIONAL INSURANCE"),
	ORIENTALINSURANCE(14,"ORIENTAL INSURANCE CO. LTD"),
	LIBERTY_VIDEOCON(15,"LIBERTY VIDEOCON GENERAL INSCOLTD"),
	SBI_GENERAL(16,"SBI GENERAL INSURANCE COMPANY LTD"),
	ORIENTAL_INSURANCE_CO(17,"ORIENTAL INSURANCE CO."),
	CHOLA_MANDALAM(18,"CHOLA MANDALAM INSURANCE CO LTD"),
	L_AND_T_INSURANCE(19,"L AND T INSURANCE COMPANY"),
	MAGMA_HDI(20,"MAGMA HDI GENERAL INSURANCECOMP LTD"),
	SHRIRAM_GENERAL(21,"SHRIRAM GENERAL INSURANCE CO LTD"),
	THE_ROYAL_SUNDRAM(22,"THE ROYAL SUNDRAM INSURANCE CO LTD"),
	RELIANCE_LIFE_INSURANCE(23,"RELIANCE LIFE INSURANCE COMPANY LTD");
	
	
	
	private final int id;
	private final String name;
	PreviousInsurersEnum(int id,String name){
		this.id=id;
		this.name= name;
	}
	public int getId() {
		return id;
	}
	public String getName() {
		return name;
	}
	
}
