package com.sharktank.entity;

// default package
// Generated 8 Dec, 2018 3:19:18 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", catalog = "sharktank")
public class Company implements java.io.Serializable {

	private Integer id;
	private Integer season;
	private Integer noInSeries;
	private String name;
	private Boolean deal;
	private String industry;
	private String gender;
	private Double equity;
	private Double valuation;
	private String notes;
	private Set<CompanyInvestor> companyInvestors = new HashSet<CompanyInvestor>(0);

	public Company() {
	}

	public Company(Integer season, Integer noInSeries, String name, Boolean deal, String industry, String gender,
			Double equity, Double valuation, String notes, Set<CompanyInvestor> companyInvestors) {
		this.season = season;
		this.noInSeries = noInSeries;
		this.name = name;
		this.deal = deal;
		this.industry = industry;
		this.gender = gender;
		this.equity = equity;
		this.valuation = valuation;
		this.notes = notes;
		this.companyInvestors = companyInvestors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "season")
	public Integer getSeason() {
		return this.season;
	}

	public void setSeason(Integer season) {
		this.season = season;
	}

	@Column(name = "no_in_series")
	public Integer getNoInSeries() {
		return this.noInSeries;
	}

	public void setNoInSeries(Integer noInSeries) {
		this.noInSeries = noInSeries;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "deal")
	public Boolean getDeal() {
		return this.deal;
	}

	public void setDeal(Boolean deal) {
		this.deal = deal;
	}

	@Column(name = "industry", length = 100)
	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "equity", precision = 22, scale = 0)
	public Double getEquity() {
		return this.equity;
	}

	public void setEquity(Double equity) {
		this.equity = equity;
	}

	@Column(name = "valuation", precision = 22, scale = 0)
	public Double getValuation() {
		return this.valuation;
	}

	public void setValuation(Double valuation) {
		this.valuation = valuation;
	}

	@Column(name = "notes", length = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<CompanyInvestor> getCompanyInvestors() {
		return this.companyInvestors;
	}

	public void setCompanyInvestors(Set<CompanyInvestor> companyInvestors) {
		this.companyInvestors = companyInvestors;
	}

}
