package com.sharktank.entity;

// default package
// Generated 8 Dec, 2018 3:19:18 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Investor generated by hbm2java
 */
@Entity
@Table(name = "investor", catalog = "sharktank")
public class Investor implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createdOn;
	private Set<CompanyInvestor> companyInvestors = new HashSet<CompanyInvestor>(0);

	public Investor() {
	}

	public Investor(String name) {
		this.name = name;
	}

	public Investor(String name, Date createdOn, Set<CompanyInvestor> companyInvestors) {
		this.name = name;
		this.createdOn = createdOn;
		this.companyInvestors = companyInvestors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "investor")
	public Set<CompanyInvestor> getCompanyInvestors() {
		return this.companyInvestors;
	}

	public void setCompanyInvestors(Set<CompanyInvestor> companyInvestors) {
		this.companyInvestors = companyInvestors;
	}

}
